### ISSUE TITLE
Maker improvements

### ISSUE THREAD

**Issue by sebheitzmann** [2lenet/CruditBundle#13]
- Choix de l'entité : C'est top

- Mode strict ou non :  C'est pas la peine à mon avis on peux le forcer.

- générer ou non un contrôleur : On va forcer les controlleur. C'est plus explicite et plus clair.
- Namespace : par défaut, il faudrait que ce soit App\Controller\Crudit\ : Si je change, le répertoire n'est pas correctement généré
![image](https://user-images.githubusercontent.com/2197902/112163179-1160d200-8bed-11eb-813b-da145838557a.png)

Au niveau du code : 

```php
class EspeceController extends AbstractCrudController
{
    /** @var ConfigProvider  */
    private $configProvider;

    public function __construct(ConfigProvider $configProvider)
    {
        $this->configProvider = $configProvider;
    }

    /**
     * @Route("/")
     */
    public function index(Request $request): Response
    {
        $views = $this->getBrickBuilder()->build($this->configProvider->get(EspeceCrudConfig::class), $request);
        return $this->render('@LleCrudit/crud/index.html.twig', ['views' => $views]);
    }
```

je pense que c'est mieux d'injecter directement le CrudConfig dans le controlleur. A quoi ça sert d'avoir un configProvider ? C'est un registre qui fait exactement la même chose que le Container. Donc pas utile.

![image](https://user-images.githubusercontent.com/2197902/112163835-aebc0600-8bed-11eb-989a-75227a322331.png)

pourquoi "DéfaultDatasource" ? getDatasource c'est suffisant. y'a pas de moyen d'en avoir plusieurs de toute manière. C'est le datasource du crud.

Dernier point : je pense qu'il faudrait rendre optionnel la possibilité de mettre le menu ou pas. Par défaut on le met.

**Comment by jorissae** [comment]
Le "default" viens du fait que par defaut les brick sans datasource vont s'y branché (si besoin).

Mais je ne vois pas inconvénient a renommé par getDatasource.

**Comment by sebheitzmann** [comment]
tu pourra voir le reste aussi ? Pour le moment on va générer que quelques entités.
